# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/ugrads/s/samuel.fafel/Desktop/ecen449/project_2/project_2.cache/wt [current_project]
set_property parent.project_path /home/ugrads/s/samuel.fafel/Desktop/ecen449/project_2/project_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files /home/ugrads/s/samuel.fafel/Desktop/ecen449/project_2/project_2.srcs/sources_1/bd/led_sw/led_sw.bd
set_property used_in_implementation false [get_files -all /home/ugrads/s/samuel.fafel/Desktop/ecen449/project_2/project_2.srcs/sources_1/bd/led_sw/ip/led_sw_microblaze_0_0/led_sw_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/s/samuel.fafel/Desktop/ecen449/project_2/project_2.srcs/sources_1/bd/led_sw/ip/led_sw_microblaze_0_0/led_sw_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/s/samuel.fafel/Desktop/ecen449/project_2/project_2.srcs/sources_1/bd/led_sw/ip/led_sw_microblaze_0_0/led_sw_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/s/samuel.fafel/Desktop/ecen449/project_2/project_2.srcs/sources_1/bd/led_sw/ip/led_sw_dlmb_v10_0/led_sw_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/s/samuel.fafel/Desktop/ecen449/project_2/project_2.srcs/sources_1/bd/led_sw/ip/led_sw_dlmb_v10_0/led_sw_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/s/samuel.fafel/Desktop/ecen449/project_2/project_2.srcs/sources_1/bd/led_sw/ip/led_sw_ilmb_v10_0/led_sw_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/s/samuel.fafel/Desktop/ecen449/project_2/project_2.srcs/sources_1/bd/led_sw/ip/led_sw_ilmb_v10_0/led_sw_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/s/samuel.fafel/Desktop/ecen449/project_2/project_2.srcs/sources_1/bd/led_sw/ip/led_sw_dlmb_bram_if_cntlr_0/led_sw_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/s/samuel.fafel/Desktop/ecen449/project_2/project_2.srcs/sources_1/bd/led_sw/ip/led_sw_ilmb_bram_if_cntlr_0/led_sw_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/s/samuel.fafel/Desktop/ecen449/project_2/project_2.srcs/sources_1/bd/led_sw/ip/led_sw_lmb_bram_0/led_sw_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/s/samuel.fafel/Desktop/ecen449/project_2/project_2.srcs/sources_1/bd/led_sw/ip/led_sw_mdm_1_0/led_sw_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/s/samuel.fafel/Desktop/ecen449/project_2/project_2.srcs/sources_1/bd/led_sw/ip/led_sw_mdm_1_0/led_sw_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/s/samuel.fafel/Desktop/ecen449/project_2/project_2.srcs/sources_1/bd/led_sw/ip/led_sw_mdm_1_0/led_sw_mdm_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/s/samuel.fafel/Desktop/ecen449/project_2/project_2.srcs/sources_1/bd/led_sw/ip/led_sw_clk_wiz_1_0/led_sw_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/s/samuel.fafel/Desktop/ecen449/project_2/project_2.srcs/sources_1/bd/led_sw/ip/led_sw_clk_wiz_1_0/led_sw_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/s/samuel.fafel/Desktop/ecen449/project_2/project_2.srcs/sources_1/bd/led_sw/ip/led_sw_clk_wiz_1_0/led_sw_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/s/samuel.fafel/Desktop/ecen449/project_2/project_2.srcs/sources_1/bd/led_sw/ip/led_sw_rst_clk_wiz_1_100M_0/led_sw_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/s/samuel.fafel/Desktop/ecen449/project_2/project_2.srcs/sources_1/bd/led_sw/ip/led_sw_rst_clk_wiz_1_100M_0/led_sw_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/s/samuel.fafel/Desktop/ecen449/project_2/project_2.srcs/sources_1/bd/led_sw/ip/led_sw_rst_clk_wiz_1_100M_0/led_sw_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/s/samuel.fafel/Desktop/ecen449/project_2/project_2.srcs/sources_1/bd/led_sw/ip/led_sw_axi_gpio_0_0/led_sw_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/s/samuel.fafel/Desktop/ecen449/project_2/project_2.srcs/sources_1/bd/led_sw/ip/led_sw_axi_gpio_0_0/led_sw_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/s/samuel.fafel/Desktop/ecen449/project_2/project_2.srcs/sources_1/bd/led_sw/ip/led_sw_axi_gpio_0_0/led_sw_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/s/samuel.fafel/Desktop/ecen449/project_2/project_2.srcs/sources_1/bd/led_sw/ip/led_sw_xbar_0/led_sw_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/ugrads/s/samuel.fafel/Desktop/ecen449/project_2/project_2.srcs/sources_1/bd/led_sw/led_sw_ooc.xdc]
set_property is_locked true [get_files /home/ugrads/s/samuel.fafel/Desktop/ecen449/project_2/project_2.srcs/sources_1/bd/led_sw/led_sw.bd]

read_verilog -library xil_defaultlib /home/ugrads/s/samuel.fafel/Desktop/ecen449/project_2/project_2.srcs/sources_1/bd/led_sw/hdl/led_sw_wrapper.v
read_xdc /home/ugrads/s/samuel.fafel/Desktop/ecen449/project_2/project_2.srcs/constrs_1/new/led.xdc
set_property used_in_implementation false [get_files /home/ugrads/s/samuel.fafel/Desktop/ecen449/project_2/project_2.srcs/constrs_1/new/led.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top led_sw_wrapper -part xc7z020clg400-1
write_checkpoint -noxdef led_sw_wrapper.dcp
catch { report_utilization -file led_sw_wrapper_utilization_synth.rpt -pb led_sw_wrapper_utilization_synth.pb }
