obj-m += multiplier.o
obj-m += multiply.o
obj-m += hello.o

all:
	make -C /home/ugrads/s/samuel.fafel/Desktop/ecen449/Lab5/linux-3.14 M=$(PWD) modules

clean:
	make -C /home/ugrads/s/samuel.fafel/Desktop/ecen449/Lab5/linux-3.14 M=$(PWD) clean
